# Generated by Django 4.1.4 on 2022-12-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('model', models.IntegerField(primary_key=True, serialize=False)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('hd', models.IntegerField(blank=True, null=True)),
                ('screen', models.FloatField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'laptops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pcs',
            fields=[
                ('model', models.IntegerField(primary_key=True, serialize=False)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('ram', models.IntegerField(blank=True, null=True)),
                ('hd', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pcs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('model', models.IntegerField(primary_key=True, serialize=False)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'printers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('maker', models.CharField(blank=True, max_length=5, null=True)),
                ('model', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
